# Generated by Django 2.1.2 on 2019-04-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadlink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.PositiveIntegerField(max_length=10)),
                ('productlink', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
