# Generated by Django 2.1.2 on 2019-04-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20190421_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadlink',
            old_name='productid',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='downloadlink',
            old_name='productlink',
            new_name='product_link',
        ),
    ]
