# Generated by Django 2.1.2 on 2019-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20190421_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='product_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='product_link',
            field=models.CharField(max_length=10000),
        ),
    ]
