# Generated by Django 2.1.2 on 2019-06-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20190421_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
