# Generated by Django 2.1.2 on 2019-06-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0005_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlink',
            name='link_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
