# Generated by Django 2.1.2 on 2019-06-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0006_downloadlink_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='product_link',
            field=models.CharField(max_length=800),
        ),
    ]
