# Generated by Django 2.1.2 on 2019-01-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questionConttent', models.CharField(max_length=200, unique=True)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
