# Generated by Django 2.1.2 on 2019-02-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=50, unique=True, verbose_name='登录账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=8, verbose_name='姓名')),
                ('sex', models.CharField(max_length=1, verbose_name='性别')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('gradeClass', models.CharField(max_length=15, verbose_name='年级班级')),
                ('registerTime', models.DateTimeField(auto_now=True, verbose_name='注册日期')),
            ],
        ),
    ]
