# Generated by Django 2.1.2 on 2019-02-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
