# Generated by Django 2.1.2 on 2019-03-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_message_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('estimatedTime', models.CharField(max_length=50)),
                ('remainingTime', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
    ]
